### ISSUE TITLE
Lesson 1 - Revision

### ISSUE THREAD

**Issue by tolkien111** [tolkien111/Java#1]
# Acceptance Criteria ✅ 

- [x] The user is able to perform 4 basic operations: `+`/`-`/`*`/`/`
- [x] The user is doing the operations till the exit command is provided (f.eg. exit/quit etc.), once such a command would be provided, the app should stop
- [x] The user is able to check the calculation history (once the app is closed, the history is cleared i.e.: it's not saved in DB)
- [x] The [MVC ](https://medium.com/edureka/mvc-architecture-in-java-a85952ae2684) pattern has been implemented

# Description 📎 

Create the simple `Calculator` app with the console user interface. The main loop should finish once the exit/quit command would be provided, psb:

```java
String operation = "";
while(!operation.equals("quit"){
  // some operations
}
```

The inputs for the app are following, all of them should be fetched from the user using the `Scanner` object in the each iteration of the loop:

- operation (`exit`, `+`, `-`, `*`, `/`),
- var1,
- var2.

Once the input data would be provided, based on the operation the app could perform proper function (addition/subtraction/multiplication/division). The suggestion is to create the static methods for all of those operations (it could be handled in the one block of code). 💪 🚀 

Good luck 🤞 .

All of the processes related to the GIT/Task workflow must be performed.

# Documentation 📚 

## GIT commands 👨‍💻 

![Image](https://user-images.githubusercontent.com/79418084/257003554-17118e7e-2835-4df0-a8a2-3b4f677fdcdd.png)

Useful commands:
- `git fetch`/`git pull` - repo update,
- `git add *.java` - add *.java files to stage area,
- `git commit -m "#123 Task title" `- changes commit,
- `git push` - pushing the commit into the remote repo,
- `git status` - status check,
- `git branch -r` - listing all remote branches,
- `git branch -l` - listing all local brnaches,
- `git log` - commits history,
- `git checkout 123-task-title` - switching branches,
- `git diff` - checking the difference between local **unstaged** changes and the remote one,
- `git diff --cached` - checking the difference between local **staged** changes and the remote one.

## GIT branched 🌳 

![Image](https://user-images.githubusercontent.com/79418084/257003582-a76976be-5cb6-4070-8418-168400f790c8.png)

## Task lifecycle 📦 

![Image](https://user-images.githubusercontent.com/79418084/257003606-86dd7537-1907-4058-8437-b47423ce5879.png)
